spring.datasource.url = ${DB_URL:jdbc:mysql://localhost:3306/base?useSSL=false}
spring.datasource.username = ${DB_USERNAME:root}
spring.datasource.password = ${DB_PASSWORD:n@5b2F2rme^Bxj$65&FY}
spring.jpa.hibernate.ddl-auto = update
# indicas a tu aplicación Spring Boot el uso de códigos ANSI para formatear la salida de texto en la consola para el uso de colores y otros estilos visuales
spring.output.ansi.enabled=always
